Posyandu/urls.py
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('input', views.input, name='input'),
    path('posyandu/<int:nik>', views.inputposyandu, name='posyandu'),
    path('action/', views.action, name='action'),
    # Riwayat Dusun
    path('riwayat', views.riwayat, name='riwayat'),
    path('riwayat/kadipeso', views.kadipeso, name='kadipeso'),
    path('riwayat/dumpul', views.dumpul, name=''),
    path('riwayat/derso', views.derso, name=''),
    path('riwayat/sumberejo', views.sumberejo, name=''),
    path('riwayat/plandakan', views.plandakan, name=''),
    path('riwayat/kerjo', views.kerjo, name=''),
    path('riwayatfilter', views.filtered, name='riwayatfilter'),
    path('login', views.login_request, name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout')
]

main/models.py
from django.db import models

# Create your models here.
class Profil(models.Model):
    nik     = models.IntegerField()
    nama    = models.CharField(max_length=40)
    tgl     = models.DateField()
    kelamin = models.CharField(max_length=10)
    namaibu = models.CharField(max_length=40)
    nikibu  = models.IntegerField()
    dusun  = models.CharField(max_length=30, default='Sumberejo')

    def __str__(self):
        return f"{self.nik}, {self.nama}, {self.namaibu}"
    
class Posyandu(models.Model):
    bulan  = models.CharField(max_length=20, default='Januari')
    nik = models.ForeignKey(Profil, on_delete=models.CASCADE)
    tb  = models.IntegerField()
    bb  = models.IntegerField()
    ll  = models.IntegerField()
    lk  = models.IntegerField()
    ket = models.CharField(max_length=20,)

    def __str__(self):
        return f"{self.nik.nama}, {self.bulan}, {self.tb}, {self.bb}"

main/forms.py
from django import forms
from dal import autocomplete
from django.shortcuts import  render, redirect
from django.contrib.auth import login, authenticate #add this
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm #add this

class SearchBalita(forms.Form):
    nama = forms.CharField(
        max_length=50,
        label = '',
        label_suffix= '',
        widget=forms.TextInput(attrs={
            'placeholder' : 'Nama'
        })
    )
class BulanForm(forms.Form):
    pilihanbulan = [
    ('Januari', 'Januari'),
    ('Februari', 'Februari'),
    ('Maret', 'Maret'),
    ('April', 'April'),
    ('Mei', 'Mei'),
    ('Juni', 'Juni'),
    ('Juli', 'Juli'),
    ('Agustus', 'Agustus'),
    ('September', 'September'),
    ('Oktober', 'Oktober'),
    ('November', 'November'),
    ('Desember', 'Desember'),
]
    bulan = forms.ChoiceField(
        widget = forms.Select,
        choices = pilihanbulan,
        label = 'Posyandu Bulan'

    )

class ProfilInput(forms.Form):
    nik = forms.IntegerField(
        label_suffix = ' ',
        label = ' ',
        widget=forms.TextInput(attrs={
            'placeholder' : 'NIK'
        })
    )
    nama = forms.CharField(
        max_length=30,
        label=' ', 
        label_suffix=' ',
        widget=forms.TextInput(attrs={
            'placeholder' : 'Nama Lengkap'
        })
    )
    namaibu = forms.CharField(
        max_length=30,
        label = '',
        label_suffix='',
        widget=forms.TextInput(attrs= {
            'placeholder' : 'Nama Ibu'
        })
    )
    nikibu = forms.IntegerField(
        required=True,
        label_suffix='',
        label = '',
        widget = forms.TextInput(attrs = {
            'placeholder' : 'NIK Ibu'
        })
    )
    pilihandusun = [
        ('Kerjo', 'Kerjo'),
        ('Sumberejo', 'Sumberejo'),
        ('Plandakan', 'Plandakan'),
        ('Kadipeso', 'Kadipeso'),
        ('Dumpul', 'Dumpul'),
        ('Derso', 'Derso')
    ]
    dusun = forms.ChoiceField(
        widget=forms.Select(attrs={
            'class' : 'dusun'
        }),
        required = True,
        choices=pilihandusun,
        label = 'Dusun',
    )
    tgl = forms.DateField(
        label=' ', 
        label_suffix=' ',
        widget=forms.DateInput(attrs={
            'placeholder' : 'Tanggal Lahir',
            'class' : 'tgl',
            'type' : 'date'
        }))
    
    pilihankelamin = [
        ('Laki-laki', 'Laki-laki'),
        ('Perempuan', 'Perempuan')
    ]
    kelamin = forms.ChoiceField(
        widget = forms.RadioSelect,
        choices = pilihankelamin,
        label = "Jenis Kelamin "
    )   

class PosyanduForm(forms.Form):
    pilihanbulan = [
    ('Januari', 'Januari'),
    ('Februari', 'Februari'),
    ('Maret', 'Maret'),
    ('April', 'April'),
    ('Mei', 'Mei'),
    ('Juni', 'Juni'),
    ('Juli', 'Juli'),
    ('Agustus', 'Agustus'),
    ('September', 'September'),
    ('Oktober', 'Oktober'),
    ('November', 'November'),
    ('Desember', 'Desember'),
]

    bulan = forms.ChoiceField(
        required = True,
        widget = forms.Select,
        choices = pilihanbulan,
        label = 'Posyandu Bulan'

    )
    bb = forms.IntegerField(
        required = True,
        label_suffix ='',
        label = '',
        widget = forms.TextInput(attrs = {
            'placeholder' : 'Berat Badan'
        })
    )
    tb = forms.IntegerField(
        required = True,
        label_suffix ='',
        label = '',
        widget = forms.TextInput(attrs = {
            'placeholder' : 'Tinggi Badan'
        })
    )
    ll = forms.IntegerField(
        required = True,
        label_suffix ='',
        label = '',
        widget = forms.TextInput(attrs = {
            'placeholder' : 'Lingkar Lengan'
        })
    )
    lk = forms.IntegerField(
        required = True,
        label_suffix ='',
        label = '',
        widget = forms.TextInput(attrs = {
            'placeholder' : 'Lingkar Kepala'
        })
    )
    ket = forms.CharField(
        required = False,
        label_suffix ='',
        label = '',
        widget = forms.TextInput(attrs = {
            'placeholder' : 'Keterangan'
        })
    )

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from datetime import date, timezone, datetime
from .forms import *
from django.db.models import Prefetch
from django.http import HttpResponse, HttpResponseRedirect, Http404
from . forms import *
from . models import *


# Create your views here.
@login_required
def index(response):
    return render(response, 'index.html')

@login_required
def input(response):
    if response.method == 'POST':
        
        profilform = ProfilInput(response.POST)

        if profilform.is_valid():
            nik = profilform.cleaned_data['nik']
            nama = profilform.cleaned_data['nama']
            nikibu = profilform.cleaned_data['nikibu']
            tgl = profilform.cleaned_data['tgl']
            kelamin = profilform.cleaned_data['kelamin']
            namaibu = profilform.cleaned_data['namaibu']
            dusun = profilform.cleaned_data['dusun']

        p = Profil(nik=nik, nama=nama, tgl=tgl, nikibu=nikibu, dusun=dusun, kelamin=kelamin, namaibu=namaibu)
        p.save()

        profilform = ProfilInput()
        notif = "Sukses memasukan data"

        context = {
            'profilform'    : profilform,
            'notif'         : notif
        }

        return render(response, 'input.html', context)
    else:
        profilform = ProfilInput()
    
    return render(response, 'input.html', {'profilform' : profilform})

@login_required
def action(response):
    profils = Profil.objects.all()
    umur = 0

    if response.method == 'POST':
        forms = SearchBalita(response.POST)
        if forms.is_valid():
            nama = forms.cleaned_data['nama']
            
            profils = profils.filter(nama__icontains=nama)
    else:
        forms = SearchBalita()

    for profil in profils:
        date = profil.tgl
        umur = (datetime.now().date() - date).days // 7
        profil.umur = umur

    return render(response, 'action.html', {'profils' : profils, 'umur' : umur, 'forms' : forms})


@login_required
def posyandu(request, nik):
    x = Profil.objects.get(nik=nik)
    if request.method == 'POST':
        forms = PosyanduForm(request.POST, instance=x)
        if forms.is_valid():
            bulan = forms.cleaned_data['bulan']
            dusun = forms.cleaned_data['dusun']
            nik = forms.cleaned_data['nik']
            bb = forms.cleaned_data['bb']
            tb = forms.cleaned_data['tb']
            ll = forms.cleaned_data['ll']
            lk = forms.cleaned_data['lk']
            ket = forms.cleaned_data['ket']
            
            p = Profil.objects.get(nik=nik)
            p.posyandu_set.create(bulan=bulan, bb=bb, tb=tb, ll=ll, lk=lk, ket=ket, dusun=dusun)
            p.save()
            return redirect('main:action')  # Replace 'profil_list' with the actual URL name for your Profil list view
    else:
        forms = PosyanduForm()
    return render(request, 'posyandu.html', {'forms': forms, 'x' : x})

@login_required
def inputposyandu(response, nik):
    data = Profil.objects.get(nik=nik)
    if response.method == 'POST':
        forms = PosyanduForm(response.POST)
        if forms.is_valid():
            bulan = forms.cleaned_data['bulan']
            bb = forms.cleaned_data['bb']
            tb = forms.cleaned_data['tb']
            ll = forms.cleaned_data['ll']
            lk = forms.cleaned_data['lk']
            ket = forms.cleaned_data['ket']
            
            p = Profil.objects.get(nik=nik)
            p.posyandu_set.create(bulan=bulan, bb=bb, tb=tb, ll=ll, lk=lk, ket=ket)
            p.save()
            return redirect('main:action')
    else:
        forms = PosyanduForm()
    
    return render(response, 'posyandu.html', {'forms' : forms, 'data' : data})


@login_required            
def riwayat(response):
    profils = Profil.objects.prefetch_related('posyandu_set')
    if response.method == 'POST':
        forms = BulanForm(response.POST)
        if forms.is_valid():
            bulan = forms.cleaned_data['bulan']
            profils = Profil.objects.prefetch_related(
                Prefetch('posyandu_set', Posyandu.objects.filter(bulan=bulan))
            ).filter(posyandu__bulan=bulan)
        
    else:
        forms = BulanForm()
    return render(response, 'all.html', {'profils': profils, 'forms' : forms})

@login_required
def dumpul(response):
    profils = Profil.objects.prefetch_related('posyandu_set')
    profils = profils.filter(dusun='Dumpul')
    if response.method == 'POST':
        forms = BulanForm(response.POST)
        if forms.is_valid():
            bulan = forms.cleaned_data['bulan']
            profils = Profil.objects.prefetch_related(
                Prefetch('posyandu_set', Posyandu.objects.filter(bulan=bulan))
            ).filter(posyandu__bulan=bulan, dusun='Dumpul')
        
    else:
        forms = BulanForm()
    context = {
        'profils' : profils,
        'forms' : forms
    }
    return render(response, 'dusundumpul.html', context)

@login_required
def kadipeso(response):
    profils = Profil.objects.prefetch_related('posyandu_set')
    profils = profils.filter(dusun='Kadipeso')
    if response.method == 'POST':
        forms = BulanForm(response.POST)
        if forms.is_valid():
            bulan = forms.cleaned_data['bulan']
            profils = Profil.objects.prefetch_related(
                Prefetch('posyandu_set', Posyandu.objects.filter(bulan=bulan))
            ).filter(posyandu__bulan=bulan, dusun='Kadipeso')
        
    else:
        forms = BulanForm()
    context = {
        'profils' : profils,
        'forms' : forms
    }
    return render(response, 'dusunkadipeso.html', context)

@login_required
def derso(response):
    profils = Profil.objects.prefetch_related('posyandu_set')
    profils = profils.filter(dusun='Derso')
    if response.method == 'POST':
        forms = BulanForm(response.POST)
        if forms.is_valid():
            bulan = forms.cleaned_data['bulan']
            profils = Profil.objects.prefetch_related(
                Prefetch('posyandu_set', Posyandu.objects.filter(bulan=bulan))
            ).filter(posyandu__bulan=bulan, dusun='Derso')
        
    else:
        forms = BulanForm()
    context = {
        'profils' : profils,
        'forms' : forms
    }
    return render(response, 'dusunderso.html', context)

@login_required
def plandakan(response):
    profils = Profil.objects.prefetch_related('posyandu_set')
    profils = profils.filter(dusun='Plandakan')
    if response.method == 'POST':
        forms = BulanForm(response.POST)
        if forms.is_valid():
            bulan = forms.cleaned_data['bulan']
            profils = Profil.objects.prefetch_related(
                Prefetch('posyandu_set', Posyandu.objects.filter(bulan=bulan))
            ).filter(posyandu__bulan=bulan, dusun='Plandakan')
        
    else:
        forms = BulanForm()
    context = {
        'profils' : profils,
        'forms' : forms
    }
    return render(response, 'dusunplandakan.html', context)

@login_required
def kerjo(response):
    profils = Profil.objects.prefetch_related('posyandu_set')
    profils = profils.filter(dusun='Kerjo')
    if response.method == 'POST':
        forms = BulanForm(response.POST)
        if forms.is_valid():
            bulan = forms.cleaned_data['bulan']
            profils = Profil.objects.prefetch_related(
                Prefetch('posyandu_set', Posyandu.objects.filter(bulan=bulan))
            ).filter(posyandu__bulan=bulan, dusun='Kerjo')
        
    else:
        forms = BulanForm()
    context = {
        'profils' : profils,
        'forms' : forms
    }
    return render(response, 'dusunkerjo.html', context)

@login_required
def sumberejo(response):
    profils = Profil.objects.prefetch_related('posyandu_set')
    profils = profils.filter(dusun='Sumberejo')
    if response.method == 'POST':
        forms = BulanForm(response.POST)
        if forms.is_valid():
            bulan = forms.cleaned_data['bulan']
            profils = Profil.objects.prefetch_related(
                Prefetch('posyandu_set', Posyandu.objects.filter(bulan=bulan))
            ).filter(posyandu__bulan=bulan, dusun='Sumberejo')
        
    else:
        forms = BulanForm()
    context = {
        'profils' : profils,
        'forms' : forms
    }
    return render(response, 'dusunsumberejo.html', context)

@login_required
def filtered(request):
    bulan = request.GET.get('bulan')
    posyandu_list = Profil.objects.prefetch_related('posyandu_set')
    if bulan:
        profils = posyandu_list.filter(bulan=bulan)
        
        context = {
            'profils' : profils,
            'posyandu_list' : posyandu_list,
        }
        return render(request, 'riwayatfilter.html', context)

def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"you are now loged as {username}")
                return redirect("main:index")
            else:
                messages.error(request, "Invalid Username or Password")
        else:
            messages.error(request, "Invalid Username or Password")
    else:
        form = AuthenticationForm()
    return render(request, 'log/login.html', {'form' : form})

main/templates/action.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Data Balita Desa Sumberejo
{% endblock %}

{% block style %}
    <link rel='stylesheet' type='text/css' href={% static 'action.css' %}>
{% endblock %}

{% block content %}
<div class='container'>
    <div class='title'>
        <h1>Data Balita Desa Sumberejo</h1>
        <form method='POST' action=''>
            {% csrf_token %}
            {{ forms }}
            <button type='submit' name='search'>Cari Nama</button>
        </form>
    </div>
    <table>
        <thead>
        <tr>
            <th>No</th>
            <th>Posyandu</th>
            <th>NIK</th>
            <th>Nama</th>
            <th>Kelamin</th>
            <th>Dusun</th>
            <th>Tanggal Lahir</th>
            <th>Umur (minggu)</th>
            <th>Nama Ibu</th>
            <th>NIK Ibu</th>
        </tr>
        </thead>
        <tbody>
        {% for profil in profils %}
        <tr>
            <td>{{ forloop.counter }}
            <td><a href="{% url 'main:posyandu' profil.nik %}">Isi Data</a></td>
            <td>{{ profil.nik }}</td>
            <td>{{ profil.nama }}</td>
            <td>{{ profil.kelamin }}</td>
            <td>{{ profil.dusun }}</td>
            <td>{{ profil.tgl }}</td>
            <td>{{ profil.umur }}</td>
            <td>{{ profil.namaibu }}</td>
            <td>{{ profil.nikibu}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>  
</div>
{% endblock %}

main/templates/all.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Riwayat Posyandu{% endblock %}

{% block style %}
    <link rel='stylesheet' type='text/css' href={% static 'all.css' %}>
{% endblock %}

{% block content %}
<div class='container'>
    <div class='intro'>
        <h1>Riwayat Posyandu Desa Sumberejo</h1>
        <form method='POST' action=''>
            {% csrf_token %}
            {{ forms }}
            <button type='submit' name='save'>Filter</button>
        </form>
    </div>
    <table>
        <thead>
            <tr>
                <th>NIK</th>
                <th>Nama</th>
                <th>Tanggal Lahir</th>
                <th>Kelamin</th>
                <th>Nama Ibu</th>
                <th>Bulan</th>
                <th>TB</th>
                <th>BB</th>
                <th>LL</th>
                <th>LK</th>
                <th>Keterangan</th>
            </tr>
        </thead>
        <tbody>
            {% for profil in profils %}
            {% for posyandu in profil.posyandu_set.all %}
            <tr>
                <td>{{ profil.nik }}</td>
                <td>{{ profil.nama }}</td>
                <td>{{ profil.tgl }}</td>
                <td>{{ profil.kelamin }}</td>
                <td>{{ profil.namaibu }}</td>
                <td>{{ posyandu.bulan }}</td>
                <td>{{ posyandu.tb }}</td>
                <td>{{ posyandu.bb }}</td>
                <td>{{ posyandu.ll }}</td>
                <td>{{ posyandu.lk }}</td>
                <td>{{ posyandu.ket }}</td>
            </tr>
            {% endfor %}
            {% empty %}
            <tr>
                <td colspan="11">No data available</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

main/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>{% block title %}Diagnosa Stunting{% endblock %}</title>
        {% block style %}
            <link rel=stylesheet type=text/css href={% static 'base.css' %}>
        {% endblock %}
        <script type='text/javascript' src={% static 'side.js' %}></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200&display=swap" rel="stylesheet">
    </head>
    <body>
        <header>
            <div class='content'>
                <a href='/'>
                    <div class='logo'>
                        <h1><img src={% static 'assets/logo.png' %} height='65'></h1>
                    </div>
                </a>
                <ul>
                    <li>Reference</li>
                    <li>About Us</li>
                    <li id='logout'><a href="{% url 'main:logout' %}">Log Out</a></li>
                </ul>
            </div>
            {% comment %} <div class='menubar'>
                <ul>
                    <li id='data'><a href='/action'>Data Balita<a></li>
                    <li id='new'><a href='/input'>Balita baru lahir</a></li>
                    <li id='riwayat'><a href='/riwayat'>Riwayat Posyandu</a></li>
                </ul>
            </div> {% endcomment %}
        </header>
        <div class='open'>
            <button onclick='openNav()'>
                <img src={% static 'assets/menu.png' %} height='30'>
            </button>
        </div>
        
        <div id='sidebar'>
            <div>
                <h3>
                    <button onclick='closeNav()'>
                        <img src={% static 'assets/close.png' %} height='20'>
                    </button>
                </h3>
                <span>Data Balita</span>
                <a id='data' href='/action'>Data Balita</a>
                <a id='input' href='/input'>Balita Baru</a>
            </div>
            <div>
                <span>Riwayat Posyandu</span>
                <a id='desa' href='/riwayat'>Desa Sumberejo</a>
                <a id='kadipeso' href='/riwayat/kadipeso'>&rarr; Posyandu Kadipeso</a>
                <a id='dumpul' href='/riwayat/dumpul'>&rarr; Posyandu Dumpul</a>
                <a id='sumberejo' href='/riwayat/sumberejo'>&rarr; Posyandu Sumberejo</a>
                <a id='kerjo' href='/riwayat/kerjo'>&#8594; Posyandu Kerjo</a>
                <a id='plandakan' href='/riwayat/plandakan'>&rarr; Posyandu Plandakan</a>
                <a id='derso' href='/riwayat/derso'>&rarr; Posyandu Derso</a>
            </div>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

main/templates/dusunderso.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Riwayat Posyandu{% endblock %}

{% block style %}
    <link rel='stylesheet' type='text/css' href={% static 'all.css' %}>
{% endblock %}

{% block content %}
<div class='container'>
    <div class='intro'>
        <h1>Riwayat Posyandu Dusun Derso</h1>
        <form method='POST' action=''>
            {% csrf_token %}
            {{ forms }}
            <button type='submit' name='save'>Filter</button>
        </form>
        <button id='print' onclick='print()'>Print</button>
    </div>
    {% comment %} <div class='filter'>
        <form method="GET" action="{% url 'main:riwayatfilter' %}">
            <select name="bulan">
                <option value="">All</option>
                <option value="Januari">Januari</option>
                <option value="Februari">Februari</option>
                <option value="Maret">Maret</option>
                <option value="April">April</option>
                <option value="Mei">Mei</option>
                <option value="Juli">c</option>
                <option value="Juli">Juli</option>
                <option value="Agustus">Agustus</option>
                <option value="September">September</option>
                <option value="Oktober">Oktober</option>
                <option value="November">November</option>
                <option value="Desember">Desember</option>
            </select>
            <button type="submit">Filter</button>
        </form>
    </div>         {% endcomment %}
    <table>
        <thead>
            <tr>
                <th>NIK</th>
                <th>Nama</th>
                <th>Tanggal Lahir</th>
                <th>Kelamin</th>
                <th>Nama Ibu</th>
                <th>Bulan</th>
                <th>TB</th>
                <th>BB</th>
                <th>LL</th>
                <th>LK</th>
                <th>Keterangan</th>
            </tr>
        </thead>
        <tbody>
            {% for profil in profils %}
            {% for posyandu in profil.posyandu_set.all %}
            <tr>
                <td>{{ profil.nik }}</td>
                <td>{{ profil.nama }}</td>
                <td>{{ profil.tgl }}</td>
                <td>{{ profil.kelamin }}</td>
                <td>{{ profil.namaibu }}</td>
                <td>{{ posyandu.bulan }}</td>
                <td>{{ posyandu.tb }}</td>
                <td>{{ posyandu.bb }}</td>
                <td>{{ posyandu.ll }}</td>
                <td>{{ posyandu.lk }}</td>
                <td>{{ posyandu.ket }}</td>
            </tr>
            {% endfor %}
            {% empty %}
            <tr>
                <td colspan="11">No data available</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
    <script>
        function print() {
            document.getElementById("print").addEventListener("click", function() {
                window.print();
              });
        }
    </script>
{% endblock %}

main/templates/dusundumpul.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Riwayat Posyandu{% endblock %}

{% block style %}
    <link rel='stylesheet' type='text/css' href={% static 'all.css' %}>
{% endblock %}

{% block content %}
<div class='container'>
    <div class='intro'>
        <h1>Riwayat Posyandu Dusun Dumpul</h1>
        <form method='POST' action=''>
            {% csrf_token %}
            {{ forms }}
            <button type='submit' name='save'>Filter</button>
        </form>
        <button id='print' onclick='print()'>Print</button>
    </div>
    {% comment %} <div class='filter'>
        <form method="GET" action="{% url 'main:riwayatfilter' %}">
            <select name="bulan">
                <option value="">All</option>
                <option value="Januari">Januari</option>
                <option value="Februari">Februari</option>
                <option value="Maret">Maret</option>
                <option value="April">April</option>
                <option value="Mei">Mei</option>
                <option value="Juli">c</option>
                <option value="Juli">Juli</option>
                <option value="Agustus">Agustus</option>
                <option value="September">September</option>
                <option value="Oktober">Oktober</option>
                <option value="November">November</option>
                <option value="Desember">Desember</option>
            </select>
            <button type="submit">Filter</button>
        </form>
    </div>         {% endcomment %}
    <table>
        <thead>
            <tr>
                <th>NIK</th>
                <th>Nama</th>
                <th>Tanggal Lahir</th>
                <th>Kelamin</th>
                <th>Nama Ibu</th>
                <th>Bulan</th>
                <th>TB</th>
                <th>BB</th>
                <th>LL</th>
                <th>LK</th>
                <th>Keterangan</th>
            </tr>
        </thead>
        <tbody>
            {% for profil in profils %}
            {% for posyandu in profil.posyandu_set.all %}
            <tr>
                <td>{{ profil.nik }}</td>
                <td>{{ profil.nama }}</td>
                <td>{{ profil.tgl }}</td>
                <td>{{ profil.kelamin }}</td>
                <td>{{ profil.namaibu }}</td>
                <td>{{ posyandu.bulan }}</td>
                <td>{{ posyandu.tb }}</td>
                <td>{{ posyandu.bb }}</td>
                <td>{{ posyandu.ll }}</td>
                <td>{{ posyandu.lk }}</td>
                <td>{{ posyandu.ket }}</td>
            </tr>
            {% endfor %}
            {% empty %}
            <tr>
                <td colspan="11">No data available</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<script>
    function print() {
        document.getElementById("print").addEventListener("click", function() {
            window.print();
          });
    }
</script>
{% endblock %}

main/templates/forms.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Diagnosa Stunting{% endblock %}

{% block style %}
    <link rel='stylesheet' type='text/css' href={% static 'home.css' %}>
{% endblock %}

{% block content %}
    {% if notif %}
        <div class='notif'>{{ notif }}</div>
    {% endif %}
    <div class='form'>  
        <form method='POST' action=''>
            {% csrf_token %}
                {{ proba.as_p }}
                {{ dayi.as_p }}
            <button type='submit' name='save'>NEXT</button>
        </form>
    </div>
{% endblock %}

main/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Aplikasi Pengolahan Data Posyandu Desa Sumberejo
{% endblock %}

{% block style %}
    <link rel='stylesheet' type='text/css' href={% static 'index.css' %}>
{% endblock %}
{% block content %}
    <div class='index'>
        <h3>Selamat datang di</h3>
        <h1>PENDAPOS Desa Sumberejo</h1>
        <small>Pengolahan Data Posyandu Desa Sumberejo</small>
    </div>
    <div class='link'>
        <a href='input'>
            Input Data
        </a>
    </div>
{% endblock %}